default: &default
  modules:
    - articles
    - themes
    - infos
    - albums
    # - maps
  preview:
    target: preview
    prototypes_dir: "prototypes"

development:
  <<: *default

production:
  <<: *default
