default: &default
  modules:
    - articles
    - themes
    - infos
    - albums
    # - maps
  preview:
    target: preview
    dirs:
      - _sass
      - _themes
      - _layout
      - _includes
      - assets
      - css
      - fonts
      - images
    files:
      build: build.yml
      config: _config.yml
      log: jekyll.log

development:
  <<: *default

production:
  <<: *default
